[package]
name = "LatexImgGen-lib-test"
version = "0.1.0"
authors = ["Emily Traynor"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
LatexImgGen-lib = "0.1.0"
